name: Deploy

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependancies
      run: apt-get install zip
    - name: Build
      run: |
        rm -rf .git
        zip -r saddles.mcpack ./*
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: saddles.mcpack
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
